name: eploy Dist
on: [push,workflow_dispatch]
jobs: 
  test: 
    runs-on: ubuntu-latest
    steps: 
      - name: Get Code
        run: |
          echo "cloning repo .."
          echo "${{toJson(github)}}"
          git clone git@github.com:rchoudhary-techrayslabs/GitHub-Actions.git
